### ISSUE TITLE
add a new npm package for parsing SDA's maFiles

### ISSUE THREAD

**Issue by sentisso** [scholtzm/awesome-steam#29]
I created a new NPM package called [mafiles](https://github.com/SenTisso/node-mafiles), this package allows you to easily parse maFiles in Node.js, which are generated by the Steam Desktop Authenticator app.

"maFiles" are the files that [SDA](https://github.com/Jessecar96/SteamDesktopAuthenticator) generates after you migrate your account to SDA. You can use the content of those files to manage your account via an automated software, for example login to steam and send or accept trades without the need to enter a password and the 2FA code manually.

This package also supports decryption of the files, in case they were encrypted by the SDA app. Meaning that you can keep your SDA encrypted for more safety, but still be able to "read" those encrypted SDA files (by entering the password when you attempt to parse an encrypted maFile).

**Comment by Aareksio** [comment]
`maFile` is not strongly associated with SDA. Other software, for example [ASF](https://github.com/JustArchiNET/ArchiSteamFarm), make use of this format as well, but may not utilize SDA's manifest file. Focusing the functionality of a `mafiles` package around specific vendor is misleading.

**Comment by sentisso** [comment]
@Aareksio Makes sense, I'll remove the requirement for defining the location of the manifest file, since it should be very easy to do so.

But then you're gonna have to specify kinda more information about the targeted maFile, such as encryption IV, encryption key (if it is encrypted of course), the exact location of the maFile etc. but that ain't gonna be too much of problem.

I was targeting it against simplicity; just define the account id, manifest file and you're done

**Comment by Aareksio** [comment]
Your logic is not wrong by any means. The only issue is `.maFile` extension not having anything to do with SDA. It was a format used by Steam android app, which SDA adopted. The encryption is also specific to SDA, not `.maFile` extension. Thus your package is more of wrapper around SDA than generic `maFile` parser.

Since maFile format is plain JSON, having a parser package is not required. I suggest you do not make any changes in the code, just describe your package as primarily SDA helper, not maFile parser :)

**Comment by scholtzm** [comment]
You can open a PR if you want to add a package.
